### ISSUE TITLE
What is --proto_path

### ISSUE THREAD

**Issue by idkw** [sevagh/pq#108]
Hello
I have this error message when trying to parse a file: 

```
cat somefile.txt | pq --msgtype SomeMessage
```

```
thread 'main' panicked at 'protoc failed: /home/path/to/file.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

Then when I supply the `protopath`:

```
cat somefile.txt | pq --protofile /path/to/file.proto --proto_path /path/to --msgtype SomeMessage
```

```
error: Found argument '--proto_path' which wasn't expected, or isn't valid in this context
	Did you mean --protofile?

USAGE:
    pq --protofile <EXTRA_PROTO_FILE>
```

I don't understand what I should do then, is --proto_path required or not ?

**Comment by sevagh** [comment]
That's actually a message from `protoc`, the protobuf compiler. `pq` will try to execute `protoc`. `--proto_path` is an argument to protoc, not pq itself:
https://github.com/sevagh/pq/blob/13ca40fb4e6c664debc8f66686140be2a75380bc/src/discovery.rs#L82

The README says what to expect:
>Usage

new You can now pass in a proto file and have pq compile it on the fly using protoc:
```
$ pq --protofile ./tests/protos/dog.proto  --msgtype com.example.dog.Dog <./tests/samples/dog
{
  "breed": "gsd",
  "age": 3,
  "temperament": "excited"
}
```
Use PROTOC and PROTOC_INCLUDE to control the executed protoc binary and configure the -I=/proto/path argument (design copied from [prost](https://github.com/danburkert/prost/blob/master/prost-build/src/lib.rs)).

Where is your `.proto` file?
