### ISSUE TITLE
pq only follows 1 partition

### ISSUE THREAD

**Issue by minaguib** [sevagh/pq#79]
pq appears to only tail 1 partition, not all partitions in a topic.

That means that, for example, given a topic with 10 partitions and incoming messages being fairly produced into all 10, pq only outputs 10% of the messages going into the topic, silently ignoring the other 90%.

In essence, pq is best considered a.t.m. as a tool to sample messages in a topic (where the sampling rate is defined by the # of partitions in the topic).

**Comment by lpgauth** [comment]
https://github.com/adgear/pq/blob/master/stream-delimit/src/kafka_consumer.rs#L22

**Comment by sevagh** [comment]
I initially suspected that it's the Kafka Consumer that I initialize.

The docs (https://docs.rs/kafka/0.7.0/kafka/consumer/struct.Builder.html#method.with_topic) say:

>Specifies a topic to consume. All of the available partitions of the identified topic will be consumed unless overriden later using with_topic_partitions.

According to that, I should be consuming from all of the partitions.

So I'm not sure. Maybe it really is the take(1)?

**Comment by sevagh** [comment]
Which version?

**Comment by lpgauth** [comment]
https://docs.rs/kafka/0.7.0/kafka/consumer/index.html#example

```
  for ms in consumer.poll().unwrap().iter() {
    for m in ms.messages() {
      println!("{:?}", m);
    }
    consumer.consume_messageset(ms);
  }
```

I' guessing it was the latest version that you set up.

**Comment by shanipribadi** [comment]
https://github.com/shanipribadi/pq/commit/fc126aab321e3127b78462c13f7f384cb12df5d1

I'm trying out this commit to fix the above issue.

Initially pq is only consuming about 7% cpu, and it seems it's only processing very small amount of messages (120 msg/sec) even though I'm expecting a lot more, and it also couldn't keep with the producer (the data timestamp lag keep increasing).
After using the above commit pq is now using 50% cpu, and able to process about  3300 msg/sec. It's still lagging though despite not maxing out on cpu, so the lag issue might be something separate.

Should I raise a PR for the above commit?

**Comment by sevagh** [comment]
PR has been merged. When I release the fix I'll ping on this issue. Trying to fix some tooling now (I'm sick of Makefiles).

**Comment by sevagh** [comment]
@minaguib Please try this release: https://github.com/sevagh/pq/releases/tag/1.1.0

**Comment by minaguib** [comment]
@sevagh Thanks - giving it a shot.

Noticed a regression somewhere between `0.8.1` and the above `1.1.0`

In `1.1.0`, if I run pq it outputs what it retrieves fine.  If however I pipe it to anything, even `| cat`, it fails with one of 2 errors:

Either
```
thread 'main' panicked at 'Error checking if stdout is tty: EAGAIN: Try again', src/commands.rs:77:19
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

or
```
thread 'main' panicked at 'Error checking if stdout is tty: EINVAL: Invalid argument', src/commands.rs:77:19
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

So without being able to pipe to something (like jq/pv), I can't actually measure output volume properly to ascertain weather the partitioning issue is fixed ;P

**Comment by sevagh** [comment]
https://github.com/sevagh/pq/releases/tag/1.1.1

**Comment by sevagh** [comment]
I switched from libc to nix to check if stdin/stdout isatty, turns out libc worked better.

**Comment by minaguib** [comment]
@sevagh Thanks again :) . Confirming for `1.1.1`:

1. Piping is fixed
1. Consuming from multiple partitions appears to be fixed

My pq test is now outputting 20k/s instead of previous version only 600/s.  Have not validated if the 20k are actually logically correct/fair/nonduplicated.

At this rate pq is consuming 100% CPU (the topic I'm testing against has a producer rate of 100k/s).

**Comment by sevagh** [comment]
Good to hear!
