### ISSUE TITLE
Pipe `kafkacat ` to pq

### ISSUE THREAD

**Issue by romand** [sevagh/pq#87]
It would be nice to be able to pipe `kafkacat` to pq.
#86

**Comment by sevagh** [comment]
Is the only requirement for this the i32be pull request?

**Comment by romand** [comment]
yes

**Comment by sevagh** [comment]
PR merged.

**Comment by romand** [comment]
thanks @sevagh !
could you please make a release with that?

**Comment by sevagh** [comment]
Done - published on Cargo and uploaded a new static binary, version 1.3.0

**Comment by romand** [comment]
thank you!
