### ISSUE TITLE
Static releases for Windows

### ISSUE THREAD

**Issue by jyn514** [sevagh/pq#88]
The releases page only has binaries for Linux. Could you release for Windows as well?

**Comment by sevagh** [comment]
I don't use Windows and I don't know how pq works there.

**Comment by sevagh** [comment]
Do you have a Windows computer and are you willing to make a pull request?

**Comment by jyn514** [comment]
I do and I am! I actually just spend the last hour or so installing MSVC and cargo.

**Comment by jyn514** [comment]
For future windows people, here's the list of what I've done so far (will update as I progress):

1. Download [`rustup`](https://win.rustup.rs/x86_64) but don't run it just yet
2. Install [Visual Studio Installer](https://visualstudio.microsoft.com/downloads/) Community edition
3. Run the installer and install `Visual Studio Build Tools 2019`. You need the `C++ Build Tools` workload. Note that you can't just install the minimal package, you also need `MSVC C++ x64/86 Build Tools` and `Windows 10 SDK`. I think they were selected by default, but I don't remember.
4. Open `x64 Native Tools Command Prompt` from the start menu.
5. Run `rustup-init.exe` (the binary from the 1st step)
6. Close the terminal
7. Open a new terminal (it doesn't have to be native tools)
8. Clone https://github.com/Microsoft/vcpkg
9. `cd vcpkg && bootstrap-vcpkg.bat`
10. `vcpkg integrate install` in the same directory
11. `vcpkg install openssl:x64-windows` in the same directory
12. `set VCPKGRS_DYNAMIC=1`
13. `cargo install pq` (in the same directory? haven't tested)

Unfortunately, the last `cargo install` doesn't save your progress if you have an error, so after you fix it you'll have to recompile all 94 dependencies.

**Comment by jyn514** [comment]
@sevagh  I get a compile error from `pq` at the very last step, I think you're depending on parts of `libc` that aren't in Windows. Traceback:

```
   Compiling pq v1.2.2
error[E0425]: cannot find value `STDIN_FILENO` in module `libc`
  --> C:\Users\Joshua\.cargo\registry\src\github.com-1ecc6299db9ec823\pq-1.2.2\src\commands.rs:52:40
   |
52 |         if unsafe { libc::isatty(libc::STDIN_FILENO) != 0 } {
   |                                        ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `STDOUT_FILENO` in module `libc`
  --> C:\Users\Joshua\.cargo\registry\src\github.com-1ecc6299db9ec823\pq-1.2.2\src\commands.rs:73:50
   |
73 |     let out_is_tty = unsafe { libc::isatty(libc::STDOUT_FILENO) != 0 };
   |                                                  ^^^^^^^^^^^^^ not found in `libc`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
```

**Comment by jyn514** [comment]
If you don't mind make the code slightly less readable, you could just use `0` and `1` directly: https://stackoverflow.com/questions/13531677/stdin-fileno-undeclared-in-windows

**Comment by jyn514** [comment]
Hmm ... after that change it builds properly but I get a popup saying `Application Error - The application was unable to start correctly (0xc000007b)`. `strace` doesn't show anything besides 'thread started' message.s

**Comment by jyn514** [comment]
well I found the error at least ... I don't have `LIBEAY32.dll` or `SSLEAY32.dll` installed. By pure chance, I had an Nmap directory in my path that bundled old versions of them that crashed pq. When I took them out of path, I got reasonable error messages but no suggestion of how to fix it :/

**Comment by jyn514** [comment]
I took a look at what actually require openssl and it was kafka, which is an optional feature. Compiling with `cargo build --no-default-features` worked.

**Comment by sevagh** [comment]
As discussed, since I can't build the binaries myself, I won't release exe files - but thanks for making it Windows-compatible and providing build instructions.
